language: clojure

lein: 2.7.1

services:
 - docker
 
script:
  - lein cljsbuild once test
  - lein deploy

after_success:
  - lein cljsbuild once prod
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO_NAME_EXTENSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo ""; else echo -$TRAVIS_BRANCH ; fi`
  - export REPO=microbusiness/microbusinessweb$REPO_NAME_EXTENSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - cd "$TRAVIS_BUILD_DIR"
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/micro-business/micro-business.github.io.git
  - cd micro-business.github.io
  - git rm -r js
  - git rm index.html
  - mkdir -p js/compiled
  - cp -f ../resources/public/index.html . 
  - cp -f ../resources/public/js/compiled/microbusinessweb.js js/compiled/
  - git add index.html
  - git add js/compiled/microbusinessweb.js
  - git commit -m "Deploying latest web files"
  - git push
  - cd ..
