language: clojure

services:
 - docker
 
script:
  - lein cljsbuild once test
  - lein cljsbuild once prod

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO_NAME_EXTENSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo ""; else echo -$TRAVIS_BRANCH ; fi`
  - export REPO=microbusiness/microbusinessweb$REPO_NAME_EXTENSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - cd "$TRAVIS_BUILD_DIR"
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/micro-business/microbusinesses.github.io.git
  - cd microbusinesses.github.io
  - mkdir -p resources/public/prod/js
  - cp -f ../resources/public/prod/index.html resources/public/prod/
  - cp -f ../resources/public/prod/js/main.js resources/public/prod/js/
  - git add resources/public/prod/index.html
  - git add resources/public/prod/js/main.js
  - git commit -m "Deploying latest web files"
  - git push
